import { describe, expect, it } from "vitest";

import { routes } from "../src/router/routes";

describe("SafeMart 路由清单", () => {
  it("包含功能型网站的核心页面路径", () => {
    const paths = routes.map((route) => route.path);

    expect(paths).toEqual([
      "/",
      "/products",
      "/login",
      "/account",
      "/orders",
      "/support",
      "/labs",
      "/status",
      "/labs/:category/:scene",
      "/labs/web/xss/vuln",
      "/labs/web/xss/fixed",
      "/labs/web/csrf/vuln",
      "/labs/web/csrf/fixed",
      "/labs/web/sql-injection/vuln",
      "/labs/web/sql-injection/fixed",
      "/labs/web/nosql-injection/vuln",
      "/labs/web/nosql-injection/fixed",
      "/labs/web/crlf-injection/vuln",
      "/labs/web/crlf-injection/fixed",
      "/labs/web/xpath-injection/vuln",
      "/labs/web/xpath-injection/fixed",
      "/labs/web/ldap-injection/vuln",
      "/labs/web/ldap-injection/fixed",
      "/labs/web/command-injection/vuln",
      "/labs/web/command-injection/fixed",
      "/labs/web/ssti/vuln",
      "/labs/web/ssti/fixed",
      "/labs/web/xxe/vuln",
      "/labs/web/xxe/fixed",
      "/labs/web/file-upload/vuln",
      "/labs/web/file-upload/fixed",
      "/labs/web/info-disclosure/vuln",
      "/labs/web/info-disclosure/fixed",
      "/labs/web/path-traversal/vuln",
      "/labs/web/path-traversal/fixed",
      "/labs/web/ssrf/vuln",
      "/labs/web/ssrf/fixed",
      "/labs/auth/jwt/vuln",
      "/labs/auth/jwt/fixed",
      "/labs/auth/idor/vuln",
      "/labs/auth/idor/fixed",
      "/labs/auth/privilege-escalation/vuln",
      "/labs/auth/privilege-escalation/fixed",
      "/labs/auth/brute-force/vuln",
      "/labs/auth/brute-force/fixed",
      "/labs/auth/session-fixation/vuln",
      "/labs/auth/session-fixation/fixed",
      "/labs/network/port-scan/vuln",
      "/labs/network/port-scan/fixed",
      "/labs/network/dns-hijack/vuln",
      "/labs/network/dns-hijack/fixed",
      "/labs/ai/prompt-injection/vuln",
      "/labs/ai/prompt-injection/fixed",
      "/labs/social/phishing/vuln",
      "/labs/social/phishing/fixed",
      "/labs/social/spear-phishing/vuln",
      "/labs/social/spear-phishing/fixed",
      "/labs/social/whaling/vuln",
      "/labs/social/whaling/fixed",
      "/labs/supply-chain/dependency-confusion/vuln",
      "/labs/supply-chain/dependency-confusion/fixed",
      "/labs/infrastructure/misconfiguration/vuln",
      "/labs/infrastructure/misconfiguration/fixed",
      "/labs/:category/:scene/:variant(vuln|fixed)",
    ]);
  });
});
